LogisticWebApp/Controllers/CarsAndDriversController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Logistic.Web.Models;
using Logistic.Web.Services;
using LogisticWebApp.Data;
using Microsoft.AspNetCore.Mvc;
using Logistic.Data;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;

namespace Logistic.Web.Controllers
{
    /// <summary>
    /// Данный класс служит для управления машинами водителями, но только после того как  
    /// пользователю присвоен carrierId
    /// </summary>
    
    public class CarsAndDriversController : Controller
    {
        private readonly CarrierService _carrierService;
        private readonly ApplicationDbContext _dbContext;
        private readonly ILogger<CarsAndDriversController> _logger;
        private readonly FileUploadService _fileUploadService;

        

        public CarsAndDriversController(CarrierService carrierService, 
            ApplicationDbContext dbContext,
            ILogger<CarsAndDriversController> logger, 
            FileUploadService fileUploadService)
        {
            _carrierService = carrierService;
            _dbContext = dbContext;
            _logger = logger;
            _fileUploadService = fileUploadService;

        }

        public async Task<IActionResult> Index()
        {
            var carrierId = _carrierService.Carrier.Id;

            var model = new CarsAndDriversViewModel
            {
                Carrier = _carrierService.Carrier,
                Cars = await _carrierService.GetCars(carrierId),
                Drivers = await _carrierService.GetDrivers(carrierId)
            }
            ;


            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddCar(CarVm model, IFormFile carfile)
        {
            string filePath = null;
            if (carfile != null)
                filePath = await _fileUploadService.AddFile(carfile);


            if (!ModelState.IsValid) return this.ReturnModelErrorsAsJson();


            var car = new Car
            {
                CarrierId = _carrierService.Carrier.Id,
                Brand = model.Brand,
                Model = model.CarModel,
                StateNumber = model.StateNumber,
                Volume = model.Volume,
                IsActive = true,
                FilePath = filePath

            };
            _dbContext.Cars.Add(car);
            await _dbContext.SaveChangesAsync();

            return PartialView("_Car",car);

        }

        [HttpPost]
        public async Task<IActionResult> AddDriver(DriverVm model, IFormFile driverfile)
        {

            string filePath = null;
            if (driverfile != null)
                filePath = await _fileUploadService.AddFile(driverfile);

            if (!ModelState.IsValid) return this.ReturnModelErrorsAsJson();

            var driver = new Driver
            {
                CarrierId = _carrierService.Carrier.Id,
                Fio = model.Fio,
                PhoneNumber = model.PhoneNumber,
                IsActive = true,
                HasContract = model.HasContract,
                FilePath= filePath

            };

            _dbContext.Drivers.Add(driver);
            await _dbContext.SaveChangesAsync();

            return PartialView("_Driver",driver);
        }



        [HttpDelete]
        public async Task<IActionResult> DeleteCar(int carId )
        {

            var carrierId = _carrierService.Carrier.Id;
           var car= _dbContext.Cars.FirstOrDefault(p => p.CarrierId == carrierId && p.Id == carId);

            if (car==null) return Json ( new { Success = false, Message = "Нет такого авто" });

               if( _dbContext.RepliesToClaims.Any(r=>r.CarId== carId))
                return Json(new { Success = false, Message = "Авто уже используется в документах" });

            _dbContext.Cars.Remove(car);
           await _dbContext.SaveChangesAsync();

               return Ok(new { Success = true });
        }

        [HttpDelete]
        public async Task<IActionResult> DeleteDriver(int driverId)
        {

            var carrierId = _carrierService.Carrier.Id;
            var driver = _dbContext.Drivers.FirstOrDefault(p => p.CarrierId == carrierId && p.Id == driverId);

            if (driver == null) return Json(new { Success = false, Message = "Нет такого водителя" });

            if (_dbContext.RepliesToClaims.Any(r => r.DriverId == driverId))
                return Json(new { Success = false, Message = "Водитель уже используется в документах" });

            _dbContext.Drivers.Remove(driver);
            await _dbContext.SaveChangesAsync();

            return Ok(new { Success = true });
        }
    }
}

LogisticWebApp/Controllers/ClaimsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Logistic.Data;
using LogisticWebApp.Data;
using Logistic.Models;
using X.PagedList;
using Microsoft.AspNetCore.Localization;
using Logistic.Web.Models;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Authorization;
using Logistic.Web.Services;
using Microsoft.Extensions.Logging;
using ServiceReference1;
using static ServiceReference1.ServiceCarrierPortTypeClient;
using Microsoft.Extensions.Configuration;

namespace Logistic.Web.Controllers
{
    /// <summary>
    /// Данный класс для того чтобы пользователь мог видеть и отвечать на заявки 
    /// </summary>
    [Authorize(Policy = "RequireCarrierId")]
    
    
    public class ClaimsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly CarrierService _carrierService;
        private readonly ClaimService _claimService;
        private readonly ILogger<ClaimsController> _logger;
        private readonly IConfiguration _configuration;

        public ClaimsController(ApplicationDbContext context, CarrierService carrierService, ILogger<ClaimsController> logger, 
            ClaimService claimService,
            IConfiguration configuration
            )
        {
            _context = context;
            _carrierService = carrierService;
            _logger = logger;
            _claimService = claimService;
            _configuration = configuration;
        }


        //[ResponseCache(Duration = 100, VaryByQueryKeys = new[] { "page", "searchstring" })]
        public async Task<IActionResult> Index(int? page, string searchstring, FilterByStatus FilterByStatus, VolumeRanges? Volume, [ModelBinder(typeof(DateTimeModelBinder))] DateTime? startDate, [ModelBinder(typeof(DateTimeModelBinder))] DateTime? endDate)
        {
            
            int pageSize = Int32.Parse(_configuration["DefaultPagesize"]);
            var carrierId = _carrierService.Carrier.Id;
            var model = new ClaimsViewModel
            {
                StartDate = startDate,
                EndDate = endDate,
                Cars = await _carrierService.GetCars(carrierId),
                Drivers = await _carrierService.GetDrivers(carrierId),
                CarrierId = carrierId,
                SearchString = searchstring,
                FilterByStatus = FilterByStatus,
                Volume = Volume                 
            };

           var claimsResult =await _claimService.GetFilteredClaimsAsync(model);
            model.Claims = claimsResult.ToPagedList(page ?? 1, pageSize);

            ViewData["pagesize"] = pageSize;


            return View( model);

            
        }
      
        private void CheckModel(ModelStateDictionary modelState, ResponseViewModel model)
        {
            if (model.ArrivalDate >= model.UnloadDate)   modelState.AddModelError("UnloadDate", "дата разгрузки не может быть ранее даты подачи авто");
            
        }

        [HttpPost]
        public async Task<IActionResult> CreateResponse(ResponseViewModel model, [ModelBinder(typeof(DateTimeModelBinder))] DateTime? ArrivalDate, 
            [ModelBinder(typeof(DateTimeModelBinder))] DateTime? UnloadDate)
        {
            model.ArrivalDate = ArrivalDate;
            model.UnloadDate = UnloadDate;

            CheckModel(ModelState , model);

            if (!ModelState.IsValid) return this.ReturnModelErrorsAsJson();

            
                try
                {
                
                var proxy = new ServiceCarrierPortTypeClient(EndpointConfiguration.ServiceCarrierSoap);

                Driver driver = await _context.Drivers.FindAsync((int)model.DriverId);
                Car car = await _context.Cars.FindAsync((int)model.CarId);

                var result = await proxy.CarrierAnswerAsync(_carrierService.Carrier.Id, model.GuidOfClaimIn1S.ToString(), (DateTime)ArrivalDate, (DateTime)UnloadDate, (int) model.Cost, driver.Fio, car.ToString());
                //return Ok(result.Body.@return);

                var reply = new ReplyToClaim
                    {
                        GuidOfClaimIn1S = model.GuidOfClaimIn1S,
                        CarrierId = _carrierService.Carrier.Id,
                        ArrivalDate = ArrivalDate,
                        UnloadDate = UnloadDate,
                        Cost = model.Cost,
                        DriverId = model.DriverId,
                        CarId = model.CarId
                        
                        //   NdsState = model.NdsState

                    };
                    _context.RepliesToClaims.Add(reply);

                    await _context.SaveChangesAsync();

                    return PartialView(reply);
                }
                catch (Exception e)
                {
                    _logger.LogError(e.Message);
                    throw;
                }                

            }
         
            
          
            
        
        
    }
}

LogisticWebApp/Controllers/UserSettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Logistic.Web.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Logistic.Web.Controllers
{
    public class UserSettingsController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;

        public UserSettingsController(UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public async  Task<IActionResult> SendToken(string token)
        {
            Claim claim = new Claim("token", token);
            if (User.Identity.IsAuthenticated)
            {
                var user = await _userManager.GetUserAsync(User);

                var claimfound = (await _userManager.GetClaimsAsync(user)).FirstOrDefault(p => p.Type == "token");

                if (claimfound != null) await _userManager.RemoveClaimAsync(user, claimfound);

                await _userManager.AddClaimAsync(user, claim);

            }

            return Ok();
        }
    }
}

LogisticWebApp/Views/Shared/_Car.cshtml
@model Car
<div data-id="@Model.Id" class="row b-list-cars">
    <div class="col-md-4 b-list-cars-item">
        @Model.Brand
    </div>

    <div class="col-md-4 b-list-cars-item">
        @Model.StateNumber
    </div>

    <div class="col-md-3 b-list-cars-item">

        
        @if (Model.FilePath != null)
    {
        <a  target="_blank" class="fancybox-btn" href="@Model.FilePath">
            <i class="fa fa-image fa-2x"></i>
            </a>
            }
</div>

    <div class="col-md-1 b-list-cars-item">
        <a href="#" class="js-deleteCar"> <img src="~/images/close.png" alt=" " title=" "></a>
    </div>
</div>

LogisticWebApp/Views/Shared/_Driver.cshtml
@model Driver
<div data-id="@Model.Id" class="row b-list-cars">
    <div class="col-md-4 b-list-cars-item">
        @Model.Fio
    </div>

    <div class="col-md-4 b-list-cars-item">
        @Model.PhoneNumber
    </div>


    <div class="col-md-3 b-list-cars-item">
        @if (Model.FilePath != null)
    {
        <a target="_blank" class="fancybox-btn" href="@Model.FilePath">
            <i class="fa fa-image fa-2x"></i>
            </a>
            }
</div>

    <div class="col-md-1 b-list-cars-item">
        <a href="#" class="js-deleteDriver"> <img src="~/images/close.png" alt=" " title=" "></a>
    </div>
</div>

LogisticWebApp/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@inject Logistic.Web.Services.CarrierService CarrierService
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - логистика</title>
    <link rel="icon" href="~/favicon.png">
    <link rel="manifest" href="/manifest.json">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/PagedList.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.css" />
    <environment include="Development">
        <link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/style.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment include="Staging,Production">
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />        
    </environment>

</head>
<body>

    <header><nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <div class="container">
                <a href="#"> <img src="~/images/logo.png" alt=" " title=" "></a>
                @{await Html.RenderPartialAsync("_LoginPartial2");}
            </div>
        </nav>
    </header>


    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Яршинторг логистика</p>
        </footer>
    </div>

    <div class="d-none">
        <i id="carrierId"> @CarrierService.Carrier?.Id</i>
        </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        
       @Html.Partial("_OtherScripts")
        
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>

        <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.6/jquery.validate.unobtrusive.js"></script>
        <script src="https://npmcdn.com/tether@1.2.4/dist/js/tether.min.js"></script>
        @Html.Partial("_OtherScripts")     
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

        @RenderSection("Scripts", required: false)

    </body>
    </html>

LogisticWebApp/Views/Shared/_LoginPartial2.cshtml
@using Microsoft.AspNetCore.Identity
@using Logistic.Web.Models
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@inject IViewLocalizer Localizer

@using Microsoft.AspNetCore.Mvc.Localization



@if (SignInManager.IsSignedIn(User))
{
<ul class="menu-right">
    @if (User.IsInRole("Manager"))
    {
        <li><a href="@Url.Action("Index", "Manager")"><i class="ico-im task"> </i><span class="hidden-xs"> @Localizer["ListOfUsers"]</span></a></li>
    }

    <li><a href="@Url.Action("Index", "Claims")" class="offer"><i class="ico-im task"> <i class="number-badge" id="numberof-activeclaims"></i></i><span class="hidden-xs"> @Localizer["ListOfClaims"]</span></a></li>
    <li><a href="@Url.Action("Index", "CarsAndDrivers")"><i class="ico-im garage"> </i><span class="hidden-xs"> @Localizer["Autopark"]  </span></a></li>
    <li class="dropdown pull-center">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle"> @UserManager.GetUserName(User)<i class="ico-im profile"></i> </a>
        <ul class="dropdown-menu">
            <li class="dropdown-menu-item"><a href="@Url.Action("Index", "UserSettings")">@Localizer["Settings"]</a></li>

            <li class="dropdown-menu-item"><a href="javascript:document.getElementById('logoutForm').submit()">@Localizer["Exit"]</a></li>

        </ul>
    </li>
</ul>
    <form hidden asp-area="" asp-controller="Account" asp-action="Logout" method="post" id="logoutForm"></form>
}
else
{
    <ul class="menu-right">
        <li><a asp-area="" asp-controller="Account" asp-action="Register">@Localizer["Register"]</a></li>
        <li><a asp-area="" asp-controller="Account" asp-action="Login">@Localizer["Login"]</a></li>
    </ul>

}

LogisticWebApp/Views/Shared/_OtherScripts.cshtml
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/momentjs/latest/moment-with-locales.min.js"></script>
<script src="https://cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js"></script>